USE [CSFD_ML]
GO

CREATE TABLE [dbo].[users](
	[user_id] [int] NULL
) ON [PRIMARY]
GO

CREATE CLUSTERED INDEX [IX_TableUser_User_ID] ON [dbo].[users]
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO